### ISSUE TITLE
REST api GET requests should not modify state

### ISSUE THREAD

**Issue by electricjay** [floodlight/floodlight#488]
Currently enabling/disabling the firewall is done via HTTP GET requests to the "REST" api.

It is best practice for GET requests to not change the state of the system.  It also has security implications related to cross site request forgery.  I suggest switching to PUT requests for these endpoints.

The PerfMon system also changes state based on GET requests and should be updated to use PUT or POST.

**Comment by rizard** [comment]
I'm taking a look at the code. Have you run all the unit tests with the changes?

**Comment by electricjay** [comment]
Ran the unit tests, but unless I missed something none of the unit tests cover the rest api. (as an aside the unmodified v1.0 source returns errors for several of the unit tests on my systems)

I tested the patch with a shell script of *curl* commands to verify there was no change to behavior (other than the GET/POST change).

**Comment by electricjay** [comment]
I have uploaded the script I used for testing as a gist: https://gist.github.com/electricjay/519f7741e8e22b65a073#file-test_rest_firewall-sh

Run the script against patched and unpatched versions of floodlight and diff the results.

**Comment by rizard** [comment]
You're right. They don't cover the REST API, but I wanted to make sure you ran them in case something else was changed inadvertently.

There is a timing and dependency issue with the unit tests that I haven't had the time to work through yet. They work for me in eclipse but not with ant on one machine of mine. The opposite is true for another machine.

If you are particularly skilled with unit tests and have the time or drive to do so, please feel free to take a look to see if you can spot the issue. I honestly have had higher priorities since they do pass given the right timing/ordering.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rizard** [comment]
@electricjay I merged your pull request a short while ago, so I'll go ahead and close this now. Thanks again for the valuable contribution!
