### ISSUE TITLE
Listening to OF messages written to the switch e.g. outgoing messages

### ISSUE THREAD

**Issue by oxisto** [floodlight/floodlight#542]
Hi folks,

in pre-1.0 versions of Floodlight it was possible for a module to listen to outgoing messages. Somehow the support for this got dropped in 1.0+. However remnants are still there, e.g. the function `handleOutgoingMessage(IOFSwitch sw, OFMessage m)` in `IFloodlightProviderService`. Is it planned to re-introduce this feature?

Currently we are working on a monitoring application to watch over incoming and outgoing OF traffic. I've re-implemented the pre-1.0 behaviour to some extend by rather crudely intercepting a `OFMessage` in the `write()` functions of `OFSwitch`. The only straightforward way to get the message from there to `IFloodlightProvider` is to provide a abstract function in the interface `IOFSwitchManager`.

Let me know what you think :)

Cheers,

Christian

**Comment by rizard** [comment]
Hi @oxisto ,

We pushed quickly to integrate OF1.3 support and it looks like this got lost in translation. It was not intentional.

As you figured out, outgoing messages are handled by the IOFSwitchService e.g. sw.write(some-OFMessage). The functionality you desire would need to be moved there, or even better, what about using the OFSwichManager (backend/implementer of IOFSwitchService)? There's a handleMessage function there around line 483 that allows the FloodlightProvider to dispatch the messages to listening modules. We would need to reference the IOFSwitchManager (included as a class variable already in OFSwitch), and then have a new function in the switch manager to handle the written message, which would then refer to the FloodlightProvider.

This would require intercepting the message in each write() function though, as you are doing now. But, I think putting the listener management in the FloodlightProvider would be better.

What are your thoughts?

**Comment by oxisto** [comment]
Hi Ryan,

That is pretty close to how I imagined it and implemented it for myself. I have introduced a new function in IOFSwitchManager called handleOutgoingMessage() similar to the one in FloodlightProvider. I've called that function in all outgoing write()-Functions of OFSwitch.

You can have a look at the changes here: https://github.com/floodlight/floodlight/compare/master...oxisto:master (just ignore the maven and gitignore changes)

If you are interested, i can try to clean up the code a little bit and prepare a pull request.

Regards,

Christian

**Comment by rizard** [comment]
@oxisto 
Hi Christian,

Sure, please clean up and issue a pull request. This will be a very useful (reintroduced) feature!

What you've done looks to be the cleanest way without significant changes. We arguably should refactor and include all message dispatching -- both OFMessages in and out -- in the switch manager. This would keep the composition of (via getOFFactory()), receiving of, and writing of OFMessages entirely within OFSwitch and OFSwitchManager. Reacting to and dispatching switch events is also housed here. 

But, that will require more work than necessary, at least for the initial pull request. If it ain't broke, don't fix it...at least for the time being ;)

Thanks,

Ryan

**Comment by rizard** [comment]
@oxisto Let me know what I can do to help you out here. Thanks!

**Comment by oxisto** [comment]
I'll prepare a pull request tomorrow!

**Comment by rizard** [comment]
@oxisto Thank you! =)

**Comment by oxisto** [comment]
Merged
