### ISSUE TITLE
Firewall rule changes do not update flow entries.

### ISSUE THREAD

**Issue by rsharo** [floodlight/floodlight#663]
## Issue

This is a known limitation of the current Firewall implementation.  Firewall only sees packet-in messages, and it can only produce an IRoutingDecision based on packet observation.

Forwarding sees the IRoutingDecision in the FloodlightContext and installs the appropriate forwarding or drop flow.  Firewall is not involved in the actual flow table population, so it doesn't know how to correct the flow table when firewall rules change.

## Proposed Solution

Add an AppCookie to IRoutingDecision.  When generating an IRoutingDecision, Firewall can place the firewall rule id in the user section of the cookie (or 0xffffffff if packet should be dropped due to rule-miss).  Forwarding can populate the cookie field in the flow-mod any way it likes -- as long as it understands the mapping from IRoutingDecision cookie to Forwarding cookie.

Firewall decision | Reason | IRoutingDecision Cookie contents
----------------------|-----------|-----------------
ALLOW | Firewall disabled | 0x00000000
ALLOW |ALLOW Rule| 32-bit rule-id
DENY | DENY Rule | 32-bit rule-id
DENY | No Matching Rule | 0xFFFFFFFF

When firewall rules change, firewall can fire a message to a (new) RoutingDecisionListener.  The message includes the AppCookie matching the changed rule, 0xffffffff if a new rule is being added, or zero if the change is global.  Examples of global changes: "enable firewall", "disable firewall", "clear firewall rules".

Upon receiving a RoutingDecisionsChanged message, Forwarding sends a flow-mod(delete) message with the appropriate cookie and cookie mask to each active switch.

Reason for RoutingDecisionsChanged | Cookie Value | Desired Effect
-------------------------------------------------|------------------|-------------------
Firewall enabled | 0 | Delete all Forwarding flows (so packets can be inspected)
Firewall disabled | 0 | Delete all Forwarding flows (or delete all DENY flows if we optimize)
Rule added | 0xFFFFFFFF or list | Delete all 'rule-miss' flows or flows matching list of rule-id's (if we optimize for overlapping matches)
Rule deleted | rule-id | delete all flows with cookie matching the rule-id

## Implications

1. Firewall behavioral change: would now push an IRoutingDecision even when firewall is disabled.  The IRoutingDecision can be a constant one constructed at application startup, though -- the cookie would always be zero when firewall is disabled.  This change allows flows to be flushed when firewall transitions "disable"->"enable".
2. Solution will only work for platforms that support cookies.  I don't think many platforms lack cookie support at this point, though.
3. Requires iteration through all active switches upon certain REST events -- something Forwarding currently never does.
4. May have to mitigate race conditions between REST threads and message pipeline.

## Questions

1. Opinions on this approach?
2. If I implement this, is there interest in merging it?

Thanks,
   Randy

**Comment by rizard** [comment]
@rsharo It sounds like you have put a lot of thought into this, and your design seems solid. We would definitely be interested in merging it with master if you have a good work solution with tests. What do you anticipate your timeframe to completion to be? We are targeting a major version bump for the beginning of June. If you could include it before then, it'd make it into the next release. Otherwise, it'd be with master thereafter. We'd be willing to push back the version bump slightly if you need the time.

One thing to note is that there are plans to use the cookie field to identify flows in the network for link failure and recovery. Each set of end-to-end flow rules installed in the network by forwarding ("flow-set") will have a unique ID in the cookie field, such that if a link or port fails for any of these flows, a network-wide flow-delete for this cookie will occur, triggering the reinstallation of flows along an alternate path, if it were to exist.

The cookie field is quite large at 64 bits, yet not large enough for comfort. We need to have a way to partition this cookie into (1) the app ID, as we do now, (2) the flow-set ID, for removal upon link/port failures, and (3) the firewall ID. Is there any way we can merge (2) and (3) into a single field within the cookie? This would allow us to maybe have 5 bits for the application ID (for a max of 32 apps...sounds somewhat reasonable) and the remaining 59 bits for the flow-set IDs, which would encompass a potentially large number of flow-sets in a large network topology or one with many very specific flow matches.

We could have forwarding use the firewall app ID in the cookie. This would logically separate the flows installed due influences of the firewall or due to vanilla forwarding. Forwarding would need to choose which app ID to use, based on the IRoutingDecision. (This solution might also double the ceiling (best case scenario) on the max supported flow-sets.) Regardless of the app ID choice though, forwarding would still keep track of the app ID + flow-set ID = whole cookie for use if/when a link/port failure occurs. The plan is to keep a map between [(switch-id, switch-port), Set<cookie>] for both the ingress and egress ports involved in each flow-mod for each flow in a flow-set.

What are your thoughts of merging this plan with yours?

**Comment by rsharo** [comment]
### Cookie Management

@rizard *Short answer:* Yes, I think all that is feasible, and I hope to have something ready before the end of May.

My intent was to have all flow-mods happen in the Forwarding (or equivalent) service.  The AppCookie provided by the IRoutingDecision is just advisory -- Forwarding is free to use or ignore any part of IRoutingDecision cookie when installing flows.  One of the nice things about rule-id being a hash is that we can take a number of bits from any part of the word and have a reasonably sparse collision space.  So if forwarding wants to only record 16 bits from the rule-id, so be it.  It just means that some "extra" flows may have to be deleted when Forwarding gets a RoutingDecisionsChanged message.  If Routing totally ignores the firewall's cookie, the design will still work -- Forwarding would just have to delete all routing flows on a RoutingDecisionsChanged. There are some tradeoffs that may suggest deleting extra flows from time to time is ok, compared to wasting time trying to figure out which flows can be left alone.  Those trades depend on how often we really think firewall rules will be changing.

Realistically, I'll probably create a configuration parameter that tells Forwarding how many Firewall cookie bits to use/mask.  Default will probably be 32 bits, or 16 if you want to save space for Link Failure.

# Link Failure and Recovery Suggestion

So, above I talked about how we can share cookie fields between Firewall and Link Failure.  But...

I'd like to offer an alternate approach for link failure recovery:  you might consider using Action Groups.  If Forwarding emits flows that use action groups instead of output actions, then all you have to do to address link failure is modify the appropriate action group(s).  This decouples the problem nicely, eliminates race conditions (since you never touch the flows themselves), and allows you to leverage silicon that supports fast-failover action buckets.

**The downside to this alternate approach is that it requires [OF1.1](http://archive.openflow.org/documents/openflow-spec-v1.1.0.pdf) or later (where action groups were added -- see Section 4.2.1).**  If you use action groups, you may have to still use the cookie solution for OF1.0 devices.

Whichever way you decide to go, my intent is to make the Firewall design work even if it has to "share" cookie bits.

**Comment by rizard** [comment]
@rsharo I considered the use of fast-failover groups to perform the failover, but as you said, it's not supported by OF1.0 and by most switch OF firmwares at this point (to my knowledge at least). Many switch forwarding ASICs do support fast-failover, but it seems it isn't exposed as a feature at this point... except maybe OF-DPA if it even is there.

Since the goal is to provide a somewhat universal solution, we need to stick with basic flow-mod operations, unfortunately. I have a separate module that uses fast-failover groups as a demo that folks can explore if they have the switches to support it.

As for the cookie, I think splitting the cookie is fine. We still need to leave space for the app ID itself, but separate firewall and forwarding partitions will work as long as it's user-configurable, which is what you're describing.

Do you think you could make use of the existing net.floodlightcontroller.core.util.AppCookie class? The user portion can be extended into the "unused" portion of the bits. Also, I think it's reasonable to shrink the app ID space from 12 bits to something much smaller. Perhaps 5 as I originally proposed or maybe up to 8, which would give a reasonably large number of possible applications. Assuming 8, that would leave 56 bits for the user portion to be divided between the forwarding and firewall for their purposes.

**Comment by rizard** [comment]
FWIW, the AppCookie class isn't used except by the static flow pusher, forwarding, and a couple other modules. it's not going to hurt to shrink the app ID portion of the AppCookie or modify the user portion.

**Comment by rsharo** [comment]
@rizard I have some of the code knocked out at this point, although nothing tested just yet.  I've made the current code available on [rsharo/floodlight/firewall_cookies](https://github.com/rsharo/floodlight/commits/firewall_cookies) if you'd like to review it, though.

### What I can tell you so far
* I'm using AppCookie and haven't had to make any major alterations.  I did add this method, however:
```
        /**
         * Returns a mask suitable for matching the App ID within a cookie.
         */
         public static U64 getAppFieldMask()
```
* Firewall now has an `APP_ID = 30`
* Message pipeline outline:
   * *Firewall disabled* -> no IRoutingDecision built (note: this is different my my original plan above)
   * *Firewall enabled* -> build a full 64-bit "decision descriptor" (would-be AppCookie) and place it in the IRoutingDecision.  Contains APP_ID and 32-bit rule-id/decision code.
   * Forwarding has a new method that generates cookies according to its own field allocation scheme (this is where I think you'd add the Link Fail logic).  Currently grabs the bottom 32-bits of the IRoutingDecision (or zero if null), and uses FORWARDING_APP_ID for the top.
```
       /**
        * Builds a cookie that includes routing decision information.
        *
        * @param decision The routing decision providing a descriptor, or null
        * @return A cookie with our app id and the required routing fields masked-in
        */
       protected U64 makeForwardingCookie(IRoutingDecision decision)
```
* Latest plans for Flow Delete:
   * Forwarding receives a RoutingDecisionsChanged message that contains a `Iterable<Masked<U64>>`.  The Firewall provides masked descriptors describing all decisions that should be revoked.
   * Forwarding translates descriptors into cookies and masks according to its own internal translation logic (currently combining FORWARDING_APP_ID with whatever parts of the descriptor's user section that are masked-in).
   * Forwarding iterates through all the switches, applying all the flow-delete methods

### Not part of the plan, but open for consideration

* *Observation*: You might want to reuse this same design to handle link failures.
   * Link Failure is another reason for "RoutingDecisionsChanged"
   * Can fire off your own event with descriptors describing the flow sets that should be rescinded.

* If you like this approach, another step would be to make Routing take an IRoutingDecision as an argument *instead of* a cookie. (I know Routing is currently ignoring the cookie parameter.)
   *  Would give Routing the ability to read any pre-decided routing intentions before picking the actual route.
   * Would allow Routing to actually alter the cookie since IRoutingDecision carries a cookie by reference. (i.e. Routing could inject a flow-set field or anything else it likes.

**Comment by rizard** [comment]
@rsharo This all sounds great to me! Feel free to follow up w/questions or comments anytime.

**Comment by rsharo** [comment]
@rizard After looking at scheduling conflicts, it looks like we will probably not be able to finish this change until maybe mid-July.  Wanted to let you know in case you were making release decisions.

Thanks,
   Randy

**Comment by rizard** [comment]
@rsharo please let us know when you're able to resume. We can wait for the release until the summer, but we'd like to get it out soon thereafter. This will be a very much improved Firewall. Thanks for your support!

**Comment by rsharo** [comment]
### Status update

@rizard Work hasn't completely stopped but I'm training a new developer as part of this update.  He's currently writing unit tests for the part you see in the [forked repo](https://github.com/rsharo/floodlight/commits/firewall_cookies).  The IRoutingDecision (message pipeline) part appears to be passing tests without a hitch.  Once unit tests are complete, he'll be writing the RoutingDecisionsChanged (REST event) part.

No changes in the schedule estimate at this point -- expecting completion mid-July.

**Comment by rizard** [comment]
@rsharo sounds good! Let us know if you have any questions along the way.

**Comment by brobertson3** [comment]
@rizard I'm the new developer that @rsharo was referring to.  I believe at this point that I have all of the new code implemented, we just have to finish verifying the changes with unit tests.  I do have a question about my implementation though.  We created an IRoutingDecisionChangedListener interface which is implemented in Forwarding.java.  We declared the methods used to add and use this listener in IRoutingService, since it was already being used by Forwarding.  Then, we added those method implementations inside of TopologyManager.java since it already implemented IRoutingService.

I wanted to know if placing logic inside of TopologyManager.java is an acceptable solution, or if there is a more preferred way to go about this.  I would greatly appreciate your input. 

Here's a link to [the diff](https://github.com/brobertson3/floodlight/compare/master...brobertson3:firewall_cookies).

Thanks in advance,
Brent

**Comment by rizard** [comment]
@brobertson3 thanks for following up on this. Let me take a closer look at your questions shortly. I'll be back in touch.

In the meantime, I do have one request. floodlight/floodlight's master branch has changed significantly since you started your work here, and there have been other conflicting changes to the topology package and to forwarding. Would you mind pulling down the recent updates to floodlight/floodlight master to your working branch and performing a merge? It'll make the diff easier to dissect and will allow use to more quickly merge your eventual pull request. Thanks!

**Comment by rizard** [comment]
@brobertson3 I agree that TopologyManager is a peculiar place to put IRoutingDecisionChangedListener registration and notification... but TopologyManger is where most of the route computation code is located. Forwarding leverages this route information. 

Since it's such a simple block of code, I'd say it's fine to include it with TopologyManager. Maybe we can eventually (TODO) refactor TopologyManager into a RoutingManager, which leverages much of what's exposed by ITopologyService to perform routing tasks only. Your code would live nicely in there along with future L3 routing code.

**Comment by brobertson3** [comment]
@rizard Thanks for taking a look at the change.  We've merged the changes from master into the working branch and we're now finishing the unit tests.  So far the functional tests look good though.  It appears that we're still on for mid-July.

**Comment by rizard** [comment]
@brobertson3 very nice! Looking forward to seeing the final result!

**Comment by rsharo** [comment]
@rizard Not sure about the etiquette -- whether the issue creator (I) should close this or leave it for the maintainer (you) to close.  Please reopen if this wasn't the right thing to do.

**Comment by rizard** [comment]
@rsharo No worries. Thanks for closing the issue. I'll knock if off my to-do list :)
