### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by sushiljain1989** [floodlight/floodlight#723]
Hi,

I am trying to run Hub(net.openfloodight.hub.Hub.java) module and registered in floodlightdefault.properties file. But it is not working for and throwing Module not found exception. Can anybody guide me over this ?

![floodlight-hubmodule](https://cloud.githubusercontent.com/assets/4305242/19683633/486a2b1e-9ab3-11e6-8a0f-6bdf05288938.png)
![floodlight](https://cloud.githubusercontent.com/assets/4305242/19683632/484e426e-9ab3-11e6-8455-076762e204b2.png)

**Comment by cbarrin** [comment]
Hi Sushil,

Sorry for the late reply, but if you haven't gotten this issue figured out
yet, trying running 'ant clean' and then running 'ant' again.

Sometimes a clean build is what it takes to solve problems like this.

Thanks!
-- 
Geddings Barrineau

On October 25, 2016 at 7:02:40 AM, Sushil Jain (notifications@github.com)
wrote:

Hi,

I am trying to run Hub(net.openfloodight.hub.Hub.java) module and
registered in floodlightdefault.properties file. But it is not working for
and throwing Module not found exception. Can anybody guide me over this ?

[image: floodlight-hubmodule]
<https://cloud.githubusercontent.com/assets/4305242/19683633/486a2b1e-9ab3-11e6-8a0f-6bdf05288938.png>
[image: floodlight]
<https://cloud.githubusercontent.com/assets/4305242/19683632/484e426e-9ab3-11e6-8455-076762e204b2.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/floodlight/floodlight/issues/723>, or mute the thread

**Comment by sushiljain1989** [comment]
Hi Geddings,

Thanks for your reply.

Sure, I'll try that and let you know the results. 


~Sushil

**Comment by LuckMonkeys** [comment]
THANKS!
