### ISSUE TITLE
guava version is too low

### ISSUE THREAD

**Issue by gwanii** [floodlight/floodlight#747]
"java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument" exception is raised in org.projectfloodlight.openflow.types.IPv4Address.ofCidrMaskLength(line298) with guava-13.0.1.jar(or guava-14.0.1.jar)

solution: upgrade to guava-20.0.jar (reference: https://github.com/grpc/grpc-java/issues/2721)

**Comment by cbarrin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #747: guava version is too low](https://trello.com/c/dYTAdKrG/37-issue-747-guava-version-is-too-low)

**Comment by cbarrin** [comment]
Are you using an older version of Floodlight? The master branch has this fix already.

**Comment by gwanii** [comment]
@cbarrin  I used floodlight 1.2.

**Comment by SoloAs** [comment]
Hey, sorry for bringing up this topic, but I got exactly same problem
The thing is, that guava dependency in pom file is 20.0 and there is 20.0 file as well as 13.0.1, but the problem still remains. If I delete 13.0.1 floodlight doesnt even start because of some missing classes
Any ideas on how to resolve that?
