### ISSUE TITLE
Static flow pusher

### ISSUE THREAD

**Issue by Horkyze** [floodlight/floodlight#781]
Inserting a static flow via foodlight ui doesnt affect the behaviour of switch.

### Steps to reproduce

Run floodligh: `java -jar target/floodlight.jar` and the mininet network
`mn --switch ovs,protocols=OpenFlow13 --controller remote`.

Upong inserting the static flow in floodlight ui like this:
<img width="1231" alt="screen shot 2018-04-09 at 10 59 22" src="https://user-images.githubusercontent.com/1040383/38488931-2f243d46-3be5-11e8-80a4-4b08a95d8e3d.png">

Verifying with tcp dump, while pinging between h1 and h2 `tcpdump -i s1-eth2 -en`, the mac address **DOES NOT** change, as it should.

Any idea what may be wrong?

**Comment by QingWang0909** [comment]
@Horkyze there're couple things might cause this problem here. Could you post the flow on the switch by doing ovs-ofctl command? That can give us an idea on what's really going on on the switch side. 

Also, could you please send emails to our Floodlight email list (floodlight-dev@openflowhub.org) for the further discussion on this problem? We typically leave out this "Issue" as the place to report bugs. Thanks for your understanding! If you send the email to our email list, we'll happy to help you there!
